sudo: required

language: java

services:
  - docker

branches:
  only:
    - travis

notifications:
  email: false
  slack:
    secure: iVMPy0WWLhjEiPrjAK0Ndmic3t7WnPdAmImMfgIGrQYoEhvBDAGGZXme1Ask9ayqxFCaqFvnTLqhvb17n+JAszaYXcQ9gBMLVpNJ0U2UMTdfE19nkguKAFkKyQDoiz17HTkDa9QMNZTfrrVgYU4KVBFxNz3zSPkeSWOrz0+wrBgzAvs9cmtQgxeUY8r1rtLe272JzOd1peyTDoYAfmJsn8kskfmkBgBfjRuVH9jYJ1CUaxZaNkSJjv0qedbjFUsITBSBvcK7XAk1H6vgwL4q7LBUbIWibk5TdX+FMejG0IPV+nDbJcDnm3ZvR1FlyJcTX2YUdbIckanUfkxVHYGAVFdiyYSQkT54fjEDZI8L9ANviGuVNTHzjzvxGrtLbQ91CqMWYcRxwwIqKiGdPC40JWQ7u+3M+1+sBNmPTHVH/6oC4+8WQYIyjoRhPeb94DvtyYvZeQ/+1nQjgHzPv7Hnw2qgqv7345BlbEtVD+H4yAKS4jWoxg2NGJM78QsfTrnU25hdMhk+0iF2R1chCExuDEq7EvFJIaXYCeoumN++r0JTscz9kyx2mzmGSmc1cXbEX3b6Lg0jaFSL1LFYJU/kz5hYyPOpS31hz2Xq9n9mpb0CVvdDxMbUGAUY8gJ+ZxYQaPnm5DfC3BSvDQHv4qGuu126TdlCk48QudqI+GMz01A=

before_install:
  - mvn clean package
  - docker build -t patrykks/iosr-zuul-service .
  - docker run --name zuul -d patrykks/iosr-zuul-service

script:
  - docker ps | grep -q zuul
  - docker exec zuul mvn -f /webapp/zuul-service/pom.xml test

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push patrykks/iosr-zuul-service;
    fi